export default function PlanResult({ plan, name, onRestart }) {
  return (
    <>
      <div className="badge badge-green">✓ Plan ready — generated by AI</div>

      <div className="welcome-box">
        {plan.welcome}
      </div>

      <div className="plan-section">
        <div className="plan-section-title">🥗 Your Diet Plan</div>
        <div className="plan-content">{plan.diet}</div>
      </div>

      <div className="divider" />

      <div className="plan-section">
        <div className="plan-section-title">🏋️ Your Workout Plan</div>
        <div className="plan-content">{plan.workout}</div>
      </div>

      <div className="divider" />

      <p style={{ fontSize: 13, color: '#666', lineHeight: 1.6 }}>
        📲 In the full system, this plan is sent automatically to the member's WhatsApp within 2 minutes of signing up.
      </p>

      <div className="restart-btn" onClick={onRestart}>
        ↩ Start over with a new member
      </div>
    </>
  )
}
